"""empty message

Revision ID: 0879b8bb65b5
Revises: d131b63cdbe0
Create Date: 2019-11-02 13:08:42.756978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0879b8bb65b5'
down_revision = 'd131b63cdbe0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('id_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'id_number')
    # ### end Alembic commands ###
