"""empty message

Revision ID: 096b491f1f6b
Revises: 42c815d33487
Create Date: 2019-04-24 19:31:43.918906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "096b491f1f6b"
down_revision = "42c815d33487"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "students",
        sa.Column("doctor_check", sa.Boolean(), nullable=False, server_default="false"),
    )
    op.add_column(
        "students",
        sa.Column("eyes_check", sa.Boolean(), nullable=False, server_default="false"),
    )
    op.add_column(
        "students",
        sa.Column("green_form", sa.Boolean(), nullable=False, server_default="false"),
    )
    op.add_column(
        "students",
        sa.Column(
            "number_of_old_lessons", sa.Integer(), nullable=False, server_default="0"
        ),
    )
    op.add_column(
        "students",
        sa.Column("theory", sa.Boolean(), nullable=False, server_default="false"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("students", "theory")
    op.drop_column("students", "number_of_old_lessons")
    op.drop_column("students", "green_form")
    op.drop_column("students", "eyes_check")
    op.drop_column("students", "doctor_check")
    # ### end Alembic commands ###
