"""empty message

Revision ID: 42c815d33487
Revises: 64169b01290d
Create Date: 2019-04-24 13:39:48.422624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "42c815d33487"
down_revision = "64169b01290d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("lesson_topics_pkey", "lesson_topics", type_="primary")
    op.execute("ALTER TABLE lesson_topics ADD COLUMN id SERIAL PRIMARY KEY")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("lesson_topics", "id")
    op.create_primary_key(
        "lesson_topics_pkey", "lesson_topics", ["lesson_id", "topic_id"]
    )
    # ### end Alembic commands ###
