"""empty message

Revision ID: 496b00960600
Revises: fe1186b9e46f
Create Date: 2019-05-02 15:30:44.874409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "496b00960600"
down_revision = "fe1186b9e46f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "teachers",
        sa.Column("crn", sa.Integer(), server_default="999999999", nullable=False),
    )
    op.add_column(
        "teachers", sa.Column("invoice_api_key", sa.String(length=240), nullable=True)
    )
    op.add_column(
        "teachers", sa.Column("invoice_api_uid", sa.String(length=240), nullable=True)
    )
    op.drop_column("teachers", "receipts_account_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "teachers",
        sa.Column(
            "receipts_account_id",
            sa.VARCHAR(length=240),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("teachers", "invoice_api_uid")
    op.drop_column("teachers", "invoice_api_key")
    op.drop_column("teachers", "crn")
    # ### end Alembic commands ###
