"""empty message

Revision ID: 53b58719e03b
Revises: 128e82ac2885
Create Date: 2019-04-11 13:49:14.083920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "53b58719e03b"
down_revision = "128e82ac2885"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "students",
        sa.Column(
            "created_at",
            sa.DateTime(),
            nullable=False,
            server_default=sa.func.current_timestamp(),
        ),
    )
    op.add_column(
        "teachers",
        sa.Column(
            "created_at",
            sa.DateTime(),
            nullable=False,
            server_default=sa.func.current_timestamp(),
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("teachers", "created_at")
    op.drop_column("students", "created_at")
    # ### end Alembic commands ###
