"""empty message

Revision ID: 62c10b7111e4
Revises: c4734f6489df
Create Date: 2019-04-01 19:52:11.577324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62c10b7111e4'
down_revision = 'c4734f6489df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'creator_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('users', sa.Column('image', sa.String(length=240), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'image')
    op.alter_column('students', 'creator_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
