"""empty message

Revision ID: 64169b01290d
Revises: 53b58719e03b
Create Date: 2019-04-17 17:29:09.098849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64169b01290d'
down_revision = '53b58719e03b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lessons', 'lesson_number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('lesson_number', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
