"""empty message

Revision ID: 744a9125a5f1
Revises: 6411fe98f46b
Create Date: 2019-06-04 15:28:46.051140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '744a9125a5f1'
down_revision = '6411fe98f46b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teachers', 'crn',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('999999999'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teachers', 'crn',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('999999999'))
    # ### end Alembic commands ###
