"""empty message

Revision ID: 8f61fb5af9c3
Revises: 62c10b7111e4
Create Date: 2019-04-05 19:18:10.403036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f61fb5af9c3'
down_revision = '62c10b7111e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('work_days', 'day',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('work_days', 'day',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
