"""empty message

Revision ID: 93bec8e22a70
Revises: ace06ccc6b5c
Create Date: 2019-01-13 17:52:20.700910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93bec8e22a70'
down_revision = 'ace06ccc6b5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('creator_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'lessons', 'users', ['creator_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lessons', type_='foreignkey')
    op.drop_column('lessons', 'creator_id')
    # ### end Alembic commands ###
