"""empty message

Revision ID: a016145093d8
Revises: 744a9125a5f1
Create Date: 2019-06-09 18:43:12.359720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a016145093d8"
down_revision = "744a9125a5f1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("places", "name", new_column_name="description", nullable=False)
    op.add_column("places", sa.Column("google_id", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("places", "description", new_column_name="name", nullable=False)
    op.drop_column("places", "google_id")
    # ### end Alembic commands ###
