"""empty message

Revision ID: b48801edfcd5
Revises: 496b00960600
Create Date: 2019-05-02 18:30:31.069318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b48801edfcd5'
down_revision = '496b00960600'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('price', sa.Integer(), nullable=True))
    op.add_column('students', sa.Column('price', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'price')
    op.drop_column('lessons', 'price')
    # ### end Alembic commands ###
