"""empty message

Revision ID: fb3286adb02b
Revises: a016145093d8
Create Date: 2019-07-15 16:27:08.144798

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "fb3286adb02b"
down_revision = "a016145093d8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "appointments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("teacher_id", sa.Integer(), nullable=False),
        sa.Column("student_id", sa.Integer(), nullable=True),
        sa.Column("duration", sa.Integer(), nullable=False),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("meetup_place_id", sa.Integer(), nullable=True),
        sa.Column("dropoff_place_id", sa.Integer(), nullable=True),
        sa.Column("is_approved", sa.Boolean(), nullable=False),
        sa.Column("comments", sa.Text(), nullable=True),
        sa.Column("deleted", sa.Boolean(), nullable=False),
        sa.Column("creator_id", sa.Integer(), nullable=False),
        sa.Column("price", sa.Integer(), nullable=True),
        sa.Column("type", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["creator_id"], ["users.id"]),
        sa.ForeignKeyConstraint(["dropoff_place_id"], ["places.id"]),
        sa.ForeignKeyConstraint(["meetup_place_id"], ["places.id"]),
        sa.ForeignKeyConstraint(["student_id"], ["students.id"]),
        sa.ForeignKeyConstraint(["teacher_id"], ["teachers.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("lessons")
    op.drop_table("tests")
    op.drop_constraint(
        "lesson_topics_lesson_id_fkey", "lesson_topics", type_="foreignkey"
    )
    op.create_foreign_key(None, "lesson_topics", "appointments", ["lesson_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "lesson_topics", type_="foreignkey")
    op.create_foreign_key(
        "lesson_topics_lesson_id_fkey",
        "lesson_topics",
        "lessons",
        ["lesson_id"],
        ["id"],
    )
    op.create_table(
        "tests",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("student_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("result", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("content", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("time", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["student_id"], ["students.id"], name="tests_student_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="tests_pkey"),
    )
    op.create_table(
        "lessons",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("teacher_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("student_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("duration", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("date", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column("is_approved", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("comments", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("deleted", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("creator_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("dropoff_place_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("meetup_place_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("price", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["creator_id"], ["users.id"], name="lessons_creator_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["dropoff_place_id"], ["places.id"], name="lessons_dropoff_place_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["meetup_place_id"], ["places.id"], name="lessons_meetup_place_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["student_id"], ["students.id"], name="lessons_student_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["teacher_id"], ["teachers.id"], name="lessons_teacher_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="lessons_pkey"),
    )
    op.drop_table("appointments")
    # ### end Alembic commands ###
