"""empty message

Revision ID: fe1186b9e46f
Revises: b2b14f5aed8a
Create Date: 2019-04-25 17:56:55.865883

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = "fe1186b9e46f"
down_revision = "b2b14f5aed8a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("payments", sa.Column("crn", sa.Integer(), nullable=True))
    op.add_column(
        "payments", sa.Column("details", sa.String(length=240), nullable=True)
    )
    op.add_column(
        "payments",
        sa.Column("payment_type", sa.Integer(), server_default="1", nullable=False),
    )
    op.add_column(
        "payments", sa.Column("pdf_link", sa.String(length=300), nullable=True)
    )
    op.add_column(
        "teachers",
        sa.Column("receipts_account_id", sa.String(length=240), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("teachers", "receipts_account_id")
    op.drop_column("payments", "pdf_link")
    op.drop_column("payments", "payment_type")
    op.drop_column("payments", "details")
    op.drop_column("payments", "crn")
    # ### end Alembic commands ###
